----------------------------------------------------------------------------------------------------
------------------------------------------AddOn NAMESPACE-------------------------------------------
----------------------------------------------------------------------------------------------------

local FOLDER_NAME, private = ...
local L = private.locale

----------------------------------------------------------------------------------------------------
-------------------------------------AUTOGENERATED NPC DATABASE-------------------------------------
----------------------------------------------------------------------------------------------------

local NPCS = {}
private.NPCS = NPCS

NPCS.npcs = {
    [182082] = { name = L["Agapanthus"] },
    [185359] = { name = L["Toklo"], sublabel = L["Fishing Trainer"] },
    [185540] = { name = L["Talendara"], sublabel = L["Inscription Trainer"] },
    [185545] = { name = L["Conflago"], sublabel = L["Alchemy Trainer"] },
    [185546] = { name = L["Metalshaper Kuroko"], sublabel = L["Blacksmithing Trainer"] },
    [185548] = { name = L["Clinkyclick Shatterboom"], sublabel = L["Engineering Trainer"] },
    [185549] = { name = L["Agrikus"], sublabel = L["Herbalism Trainer"] },
    [185551] = { name = L["Hideshaper Koruz"], sublabel = L["Leatherworking Trainer"] },
    [185553] = { name = L["Sekita the Burrower"], sublabel = L["Mining Trainer"] },
    [185556] = { name = L["Erugosa"], sublabel = L["Cooking Trainer"] },
    [185561] = { name = L["Kaestrasz"], sublabel = L["Stable Master"] },
    [185562] = { name = L["Tithris"], sublabel = L["Innkeeper"] },
    [185563] = { name = L["Jyhanna"], sublabel = L["Expert Pet Trainer"] },
    [185569] = { name = L["Gohfyrr"], sublabel = L["Alchemy and Inscription Supplies"] },
    [185570] = { name = L["Warpweaver Dayelis"], sublabel = L["Transmogrifier"] },
    [185572] = { name = L["Vekkalis"], sublabel = L["Junior Assistant Banker"] },
    [185689] = { name = L["Vaultkeeper Aleer"], sublabel = L["Void Storage"] },
    [185714] = { name = L["Imporigo"], sublabel = L["Auctioneer"] },
    [186794] = { name = L["Numernormi"], sublabel = L["Banker"] },
    [187783] = { name = L["Pakak"], sublabel = L["Fishing Supplies"] },
    [187788] = { name = L["Tukkuttok"], sublabel = L["Fishmonger"] },
    [188661] = { name = L["Expordira"], sublabel = L["Auctioneer"] },
    [188747] = { name = L["Kitror"], sublabel = L["The Roasted Ram"] },
    [189168] = { name = L["Aeoreon"], sublabel = L["Banker"] },
    [189197] = { name = L["Groundskeeper Kama"], sublabel = L["Dreamhare Herder"] },
    [189676] = { name = L["Madam Goya"], sublabel = L["Leader of the Black Market"] },
    [190084] = { name = L["Scaravelle"], sublabel = L["Crafting Orders"] },
    [190094] = { name = L["Tuluradormi"], sublabel = L["Jewelcrafting Trainer"] },
    [190839] = { name = L["Glensera"], sublabel = L["Transformation Trainer"] },
    [191000] = { name = L["Dothenos"], sublabel = L["Trade Coordinator"] },
    [193015] = { name = L["Unatos"], sublabel = L["Keeper of Renown"] },
    [193029] = { name = L["Lysindra"], sublabel = L["Pet Supplies"] },
    [193321] = { name = L["Aluri"], sublabel = L["Flight Master"] },
    [193364] = { name = L["Lithragosa"], sublabel = L["Dragonriding Trainer"] },
    [193649] = { name = L["Threadfinder Fulafong"], sublabel = L["Tailoring Trainer"] },
    [193659] = { name = L["Provisioner Thom"], sublabel = L["Blacksmithing Supplies"] },
    [193744] = { name = L["Soragosa"], sublabel = L["Enchanting Trainer"] },
    [193846] = { name = L["Ralathor the Rugged"], sublabel = L["Skinning Trainer"] },
    [194057] = { name = L["Rabul"] },
    [195768] = { name = L["Sorotis"], sublabel = L["Lead Titan Researcher"] },
    [195769] = { name = L["Weaponsmith Koref"] },
    [195770] = { name = L["Armorsmith Terisk"] },
    [195782] = { name = L["Giera"], sublabel = L["Proprietor"] },
    [195783] = { name = L["Clerk Nemora"], sublabel = L["General Goods"] },
    [195785] = { name = L["Samar"], sublabel = L["Leatherworking Supplies"] },
    [195788] = { name = L["Nallu"], sublabel = L["Fishmonger"] },
    [195850] = { name = L["Threadfinder Pax"], sublabel = L["Tailoring Trainer"] },
    [196191] = { name = L["Malicia"], sublabel = L["Scourge of the Flightless"] },
    [196516] = { name = L["Mythressa"], sublabel = L["Apprentice Primal Researcher"] },
    [196598] = { name = L["Rethelshi"], sublabel = L["Lead Primal Researcher"] },
    [196637] = { name = L["Tethalash"], sublabel = L["Quartermaster"] },
    [196640] = { name = L["Yzinia"], sublabel = L["Innkeeper"] },
    [196729] = { name = L["Gorgonzormu"], sublabel = L["Cheesemonger"] },
    [196805] = { name = L["Ryen Levenson"], sublabel = L["Baker"] },
    [196960] = { name = L["Nehmeh"], sublabel = L["Leatherworking Supplies"] },
    [196975] = { name = L["Tonko Trickybits"], sublabel = L["Sommelier"] },
    [197080] = { name = L["Cadrestrasz"], sublabel = L["Fallingwater Host"] },
    [197553] = { name = L["Fieldmaster Emberath"], sublabel = L["War Mode Quartermaster"] },
    [197574] = { name = L["Mairadormi"], sublabel = L["Innkeeper"] },
    [197911] = { name = L["Antiqdormi"], sublabel = L["Auctioneer"] },
    [198438] = { name = L["Gardener Rafalsia"], sublabel = L["Alchemy Supplies"] },
    [198441] = { name = L["Gardener Cereus"], sublabel = L["Garden Supplies"] },
    [198580] = { name = L["Kognir"], sublabel = L["Engineering Supplies"] },
    [198586] = { name = L["Shakey Flatlap"], sublabel = L["Jewelcrafting Supplies"] },
    [198587] = { name = L["Andoris"], sublabel = L["Enchanting Supplies"] },
    [198895] = { name = L["Alregosa"], sublabel = L["Portal Trainer"] },
}
